"""rename department

Revision ID: 3e5e22286827
Revises: 1e84d79c2c6e
Create Date: 2025-05-16 22:14:25.248908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5e22286827'
down_revision = '1e84d79c2c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
